export const categorias = [
  {
    id: 'prog',
    nombre: 'Programación y Desarrollo',
    descripcion: 'Cursos de programación, desarrollo web y software',
    color: '#3498db',
    codigoSeguridad: 'prog2023',
  },
  {
    id: 'design',
    nombre: 'Diseño y Creatividad',
    descripcion: 'Cursos de diseño gráfico, UX/UI y creatividad digital',
    color: '#e74c3c',
    codigoSeguridad: 'design2023',
  },
  {
    id: 'marketing',
    nombre: 'Marketing Digital',
    descripcion: 'Estrategias de marketing online y redes sociales',
    color: '#2ecc71',
    codigoSeguridad: 'mkt2023',
  },
  {
    id: 'idiomas',
    nombre: 'Idiomas',
    descripcion: 'Aprende nuevos idiomas con métodos efectivos',
    color: '#f1c40f',
    codigoSeguridad: 'lang2023',
  },
  {
    id: 'personal',
    nombre: 'Desarrollo Personal',
    descripcion: 'Mejora tus habilidades personales y profesionales',
    color: '#9b59b6',
    codigoSeguridad: 'personal2023',
  },
  {
    id: 'business',
    nombre: 'Negocios y Emprendimiento',
    descripcion: 'Aprende a crear y gestionar tu propio negocio',
    color: '#34495e',
    codigoSeguridad: 'business2023',
  },
  {
    id: 'tech',
    nombre: 'Ciencia y Tecnología',
    descripcion: 'Descubre los avances en ciencia y tecnología',
    color: '#1abc9c',
    codigoSeguridad: 'tech2023',
  },
  {
    id: 'art',
    nombre: 'Arte y Música',
    descripcion: 'Explora tu creatividad a través del arte y la música',
    color: '#e67e22',
    codigoSeguridad: 'art2023',
  }
]

export const videos = [
  {
    id: 1,
    titulo: 'Introducción a JavaScript Moderno',
    linkVideo: 'https://www.youtube.com/watch?v=z95mZVUcJ-E',
    linkImage: 'https://img.youtube.com/vi/z95mZVUcJ-E/maxresdefault.jpg',
    categoria: 'Programación y Desarrollo',
    descripcion: 'Aprende los fundamentos de JavaScript ES6+ y sus características modernas',
    duracion: '45',
    nivel: 'Principiante',
    instructor: 'Carlos Ramírez',
    codigoSeguridad: 'js2023intro',
  },
  {
    id: 2,
    titulo: 'Principios de Diseño UX/UI',
    linkVideo: 'https://www.youtube.com/watch?v=9nYqEEd-4Mo',
    linkImage: 'https://img.youtube.com/vi/9nYqEEd-4Mo/maxresdefault.jpg',
    categoria: 'Diseño y Creatividad',
    descripcion: 'Conceptos fundamentales del diseño de experiencia de usuario',
    duracion: '60',
    nivel: 'Principiante',
    instructor: 'Ana Martínez',
    codigoSeguridad: 'uxui2023',
  },
  {
    id: 3,
    titulo: 'Marketing en Redes Sociales 2023',
    linkVideo: 'https://www.youtube.com/watch?v=HW3rJwJzHHw',
    linkImage: 'https://img.youtube.com/vi/HW3rJwJzHHw/maxresdefault.jpg',
    categoria: 'Marketing Digital',
    descripcion: 'Estrategias efectivas para marketing en redes sociales',
    duracion: '55',
    nivel: 'Intermedio',
    instructor: 'Laura González',
    codigoSeguridad: 'mkt2023redes',
  },
  {
    id: 4,
    titulo: 'Inglés para Principiantes',
    linkVideo: 'https://www.youtube.com/watch?v=rWGb0orhZyw',
    linkImage: 'https://img.youtube.com/vi/rWGb0orhZyw/maxresdefault.jpg',
    categoria: 'Idiomas',
    descripcion: 'Curso básico de inglés para comenzar desde cero',
    duracion: '40',
    nivel: 'Principiante',
    instructor: 'Sarah Thompson',
    codigoSeguridad: 'eng2023basic',
  },
  {
    id: 5,
    titulo: 'Productividad y Gestión del Tiempo',
    linkVideo: 'https://www.youtube.com/watch?v=b0bZmBJJw1g',
    linkImage: 'https://img.youtube.com/vi/b0bZmBJJw1g/maxresdefault.jpg',
    categoria: 'Desarrollo Personal',
    descripcion: 'Técnicas efectivas para mejorar tu productividad',
    duracion: '35',
    nivel: 'Intermedio',
    instructor: 'Miguel Ángel Torres',
    codigoSeguridad: 'prod2023time',
  },
  {
    id: 6,
    titulo: 'Cómo Iniciar tu Startup',
    linkVideo: 'https://www.youtube.com/watch?v=r9kPGN_uM-w',
    linkImage: 'https://img.youtube.com/vi/r9kPGN_uM-w/maxresdefault.jpg',
    categoria: 'Negocios y Emprendimiento',
    descripcion: 'Guía paso a paso para crear tu startup desde cero',
    duracion: '65',
    nivel: 'Principiante',
    instructor: 'Diego Méndez',
    codigoSeguridad: 'startup2023',
  },
  {
    id: 7,
    titulo: 'Introducción a la Inteligencia Artificial',
    linkVideo: 'https://www.youtube.com/watch?v=VyDROpxKf_g',
    linkImage: 'https://img.youtube.com/vi/VyDROpxKf_g/maxresdefault.jpg',
    categoria: 'Ciencia y Tecnología',
    descripcion: 'Conceptos básicos de IA y Machine Learning',
    duracion: '50',
    nivel: 'Intermedio',
    instructor: 'Roberto Sánchez',
    codigoSeguridad: 'ai2023intro',
  },
  {
    id: 8,
    titulo: 'Teoría Musical Básica',
    linkVideo: 'https://www.youtube.com/watch?v=A0bOH7vbH60',
    linkImage: 'https://img.youtube.com/vi/A0bOH7vbH60/maxresdefault.jpg',
    categoria: 'Arte y Música',
    descripcion: 'Fundamentos de teoría musical para principiantes',
    duracion: '45',
    nivel: 'Principiante',
    instructor: 'María José Ruiz',
    codigoSeguridad: 'music2023theory',
  },
  {
    id: 9,
    titulo: 'Python para Ciencia de Datos',
    linkVideo: 'https://www.youtube.com/watch?v=gDOcR2Yc_4g',
    linkImage: 'https://img.youtube.com/vi/gDOcR2Yc_4g/maxresdefault.jpg',
    categoria: 'Programación y Desarrollo',
    descripcion: 'Aprende Python enfocado en Data Science',
    duracion: '70',
    nivel: 'Avanzado',
    instructor: 'Pablo Rodríguez',
    codigoSeguridad: 'python2023data',
  },
  {
    id: 10,
    titulo: 'Adobe Photoshop desde Cero',
    linkVideo: 'https://www.youtube.com/watch?v=rTqVukHWszE',
    linkImage: 'https://img.youtube.com/vi/rTqVukHWszE/maxresdefault.jpg',
    categoria: 'Diseño y Creatividad',
    descripcion: 'Curso completo de Photoshop para principiantes',
    duracion: '80',
    nivel: 'Principiante',
    instructor: 'Carmen Luna',
    codigoSeguridad: 'ps2023basic',
  }
]